sudo: required
services:
  - docker

before_install:
  - docker build -t cokerms/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cokerms/multi-docker npm run test

after_success:
  - docker build -t cokerms/multi-docker-client ./client
  - docker build -t cokerms/multi-docker-nginx ./nginx
  - docker build -t cokerms/multi-docker-server ./server
  - docker build -t cokerms/multi-docker-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cokerms/multi-docker-client
  - docker push cokerms/multi-docker-nginx
  - docker push cokerms/multi-docker-server
  - docker push cokerms/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-074725337699
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
